### ISSUE TITLE
No output inferred result

### ISSUE THREAD

**Issue by masterzhen119** [bluenote-1577/haplotype_phaser#11]
Given the following fragment file:
[19_floppy_.txt](https://github.com/bluenote-1577/flopp/files/11185056/19_floppy_.txt)
. I used the command:
` /home/project11/flopp/target/release/flopp -f /home/project11/Formal_simulation_SNV/New_generation_SNV_g3/Floppy_result/301/50/19_floppy_.txt  -p 3  -o /home/project11/Formal_simulation_SNV/New_generation_SNV_g3/Floppy_result/301/50/unpolished_results.txt
`
There is no output. However the simulation setting of number of haplotypes is 3. The result is as follows:
Time taken reading inputs 50.607107ms
Median read length is 1525 SNPs
Binomial adjustment factor is 61
Length of genome is 5589 SNPs
Length of each block is 0 SNPs
thread 'main' panicked at 'attempt to divide by zero', src/bin/flopp.rs:326:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

How to fix it? Since it is fine with AltHap.

**Comment by bluenote-1577** [comment]
I just pushed a new fix fixing this issue.

The issue was that some of your fragments have 0 length, so flopp panics when too many of them > 33% of them have 0 length. 

Let me know if it works.

**Comment by masterzhen119** [comment]
> I just pushed a new fix fixing this issue.
> 
> The issue was that some of your fragments have 0 length, so flopp panics when too many of them > 33% of them have 0 length.
> 
> Let me know if it works.

Thanks！ It works now！

**Comment by masterzhen119** [comment]
I found another problem. The error is :thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/utils_frags.rs:155:11
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
. My sample file is:
[01_floppy_.txt](https://github.com/bluenote-1577/flopp/files/11233242/01_floppy_.txt)
