### ISSUE TITLE
How to create a phased references in FASTA format ? 

### ISSUE THREAD

**Issue by amvarani** [bluenote-1577/haplotype_phaser#13]
Hi there,
I appreciate your effort in creating Flopp. I have a very practical question I'd like to ask: How can I create phased references in FASTA format using your tool?

Best wishes,

**Comment by bluenote-1577** [comment]
Hi @amvarani,

To create a phased fasta, you have two choices. 

1. You can just replace bases in the reference fasta with the output of flopps haplotypes along with VCF information. So if one haplotype had all alleles labeled as 1, you can replace your reference with the alternate alleles on the bases specified by your vcf. 

2. Maybe the better option is to assemble each group of read partitions output by flopp. Flopp can output groups of reads in each haplotype, and you can assemble each of these separately to get a new set of references. 

Thanks,

Jim

**Comment by amvarani** [comment]
Thanks @bluenote-1577 

It seems very simple using the get_bam_partition.py script to pick each bam, and them pbindex and bam2fastq to retrieve the fastq files. 

Best

Alessandro
