### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by ZoeVance** [bluenote-1577/haplotype_phaser#17]
Hi @bluenote-1577,

Just wondering if there are any plans to make flopp available through conda? We're planning to include it for a haplotyping step as part of a larger pipeline and it would keep the installation process simple if we could include it via conda.

Alternatively, we could equally write the recipe ourselves if you would rather, just let me know!

Thanks,
Zoe

**Comment by bluenote-1577** [comment]
Hi @ZoeVance,

I've opened up a bioconda pull request (https://github.com/bioconda/bioconda-recipes/pull/44022)

My experiences with uploading packages to conda have gone well. So hopefully that pull request goes through in a few days.  I'll poke them in a few days if it doesn't go through. 

Out of curiosity,  if you don't mind me asking, what are you using flopp to phase? 

Thanks,

Jim

**Comment by ZoeVance** [comment]
Amazing, thanks for the fast response!

We're phasing poliovirus surveillance data [piranha](https://github.com/polio-nanopore/piranha). The idea is to resolve mixed populations of reads that are mapping to the same reference polio type (i.e. cases of mixed infection, environmental samples). Polyploid phasing methods actually seem to work really well for viral haplotyping.

**Comment by bluenote-1577** [comment]
Interesting application! I'm also working on a new phasing tool to be published soon for metagenomes which may be of use: https://github.com/bluenote-1577/floria 

Notably it has some sort of method for estimating ploidy. But flopp may be sufficient for your needs.

The package is now merged into bioconda.

**Comment by ZoeVance** [comment]
Great, thanks! Will certainly check out floria - even if flopp is sufficient for this purpose there is some metagenomics work going on within the group as well so might be useful elsewhere.
