### ISSUE TITLE
index out of bounds error

### ISSUE THREAD

**Issue by mattloose** [bluenote-1577/haplotype_phaser#7]
Hi,

I'm running flopp on a sample with ploidy of 4. 

We get an error:

`thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/vcf_polishing.rs:715:9`

I do get useful output to the results file.

Is there anything helpful I can provide to you for understanding the issue further?

Thanks.

**Comment by bluenote-1577** [comment]
Hi there,

It looks like a degenerate issue with the number of SNPs or the length of your genome but that should be easily fixable. Can you provide some information on 1. the size of the genome you're phasing, 2. the number of SNPs, 3. the length of the reads? Also the flopp command you used would be helpful as well. 

I think the VCF file would be very informative. I'm not sure if you're allowed to share it, but any information about it would be helpful.

**Comment by Pottoka** [comment]
Hi !

I have same error as matloose.

```
./target/release/flopp -i -d -b ../../minimap2/NA07439.sorted.bam -v ../NA07439/noFP_filtered_merge_output.vcf -o ../result.vcf -p 2
Reading inputs (BAM/VCF/frags).
Time taken reading inputs 1.196786413s
Median read length is 29 SNPs
Binomial adjustment factor is 1.16
Length of genome is 30 SNPs
Length of each block is 28 SNPs
Estimated epsilon is 0.08142072244086818
Generating haplotype blocks
Time taken local clustering 10.963296088s
Time taken block filling 1.556µs
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/vcf_polishing.rs:715:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I work on the nanopore sequencing of a 6kb amplicon.
I used Clair3 for the Variant calling.
I need to phase the snps to identify the haplotypes in a given sample, i.e. how many and what type.

There are 30 snps in my .vcf.
My genome is 11312 pb long.
The mean reads length is 6 611 bp.
Here is the .vcf :
[noFP_filtered_merge_output.txt](https://github.com/bluenote-1577/flopp/files/10519401/noFP_filtered_merge_output.txt)

Could you help me ?
Thanks.

**Comment by bluenote-1577** [comment]
Hi @Pottoka ,

I took another look at this issue. It indeed seems to be a careless bug for small genome sizes. I should have fixed this with the latest push. Try to re-build and let me know if you have another error. 

Thanks,

Jim

**Comment by Pottoka** [comment]
It works !
Thank you very much.
