### ISSUE TITLE
log output explanation

### ISSUE THREAD

**Issue by chklopp** [bluenote-1577/haplotype_phaser#8]
Hi,

Is there a documentation for the log information produced by flopp?

Median read length is 179
Binomial adjustment factor is 7.16
Length of genome is 906443
Length of each block is 135

Input genome length is for example quite different from 906443 in my case.

**Comment by bluenote-1577** [comment]
Hi Christophe,

Thanks for the issue. This is my bad; I'll update the README and the software so it's less ambiguous. The "read length" here is _in terms of SNPS_ so it looks like the median read has 179 snps contained. The length of the genomes/block are also in terms of SNPs. So this shouldn't be an error in your inputs.

Jim
